<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class InstitutionsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('institutions')->insert([
            [
                'name' => 'Назарбаев Университет',
                'description1' => 'Назарбаев Университет — это ведущий международный исследовательский университет в Казахстане, основанный в 2010 году. Университет предлагает программы бакалавриата, магистратуры и докторантуры, следуя стандартам лучших мировых образовательных учреждений. Обучение ведётся на английском языке, а профессорско-преподавательский состав состоит из высококвалифицированных специалистов со всего мира.',
                'description2' => 'инновационный образовательный центр, созданный для подготовки высококвалифицированных специалистов в различных областях науки, инженерии, медицины и социальных наук. Университет поддерживает тесные связи с ведущими мировыми вузами и научными организациями, активно внедряя передовые технологии и методы обучения.',
                'description3' => 'Назарбаев Университет сочетает в себе академическую свободу, автономию и принцип меритократии. Здесь создаются уникальные условия для научных исследований и стартап-проектов, а выпускники становятся востребованными специалистами как в Казахстане, так и за его пределами.',
                'location' => 'Астана, Казахстан',
                'email'=> 'nu@nu.edu.kz',
                'password' => Hash::make('password123'),
                'phone'=> '+7 (7172) 70-66-88',
                'website' => 'https://nu.edu.kz',
                'created_at' => Carbon::now()->subDays(rand(1, 60)),
                'updated_at' => Carbon::now()->subDays(rand(1, 60)),
                'logo_url'=> 'https://static.tildacdn.pro/tild3836-3534-4531-b437-643930313666/NU_Logo_ENG-01.png',
                'photo_url' => 'https://vlast.kz/media/pages/8z/17103992352mfah_1600x900.jpg',
                'grants' => '1',
                'dormitory'=>'1',
                'address'=> 'просп. Кабанбай Батыра 53, Астана, Казахстан',
                'latitude' => '51.09067178404732',
                'verified' => 'accepted',
                'longitude' => '71.39816459704697',
                
            ],
            [
                'name' => 'Евразийский Национальный Университет имени Л.Н. Гумилёва',
                'description1' => 'Евразийский Национальный Университет имени Л.Н. Гумилёва (ЕНУ) — один из ведущих вузов Казахстана, основанный в 1996 году. Университет носит имя выдающегося историка и этнолога Льва Гумилёва, а его образовательные программы ориентированы на подготовку высококвалифицированных специалистов в различных областях науки, техники и гуманитарных дисциплин.',
                'description2' => 'ЕНУ имени Л.Н. Гумилёва — крупный научно-образовательный центр, активно участвующий в международных академических проектах и сотрудничестве с ведущими мировыми университетами. Университет предлагает широкий спектр программ бакалавриата, магистратуры и докторантуры, сочетая традиционные образовательные методы с современными технологиями.',
                'description3' => 'Евразийский Национальный Университет играет важную роль в развитии казахстанской науки и образования, поддерживая исследования в области истории, международных отношений, инженерии, IT и естественных наук. Университет известен своей сильной научной базой, академическими обменами и подготовкой специалистов, востребованных на мировом рынке труда.',
                'location' => 'Астана, Казахстан',
                'email'=> 'profenu@mail.ru',
               'password' => Hash::make('password123'),
                'phone'=> '+7 (7172) 70‒95‒00',
                'website' => 'https://enu.kz',
                'created_at' => Carbon::now()->subDays(rand(1, 60)),
                'updated_at' => Carbon::now()->subDays(rand(1, 60)),
                'logo_url'=> 'https://papik.pro/uploads/posts/2021-11/thumbs/1636203673_40-papik-pro-p-yenu-logotip-foto-43.png',
                'photo_url' => 'https://static.tengrinews.kz/userdata/news/2017/news_322258/thumb_m/photo_220595.jpg',
                'grants' => '1',
                'verified' => 'accepted',
                'dormitory'=>'1',
                'address'=> 'ул. Сатбаева 2, Астана Казахстан',
                'latitude' => '51.15830616351122',
                'longitude' => '71.46734210869282',
            ],
            [
                'name' => 'Казахский Агротехнический Университет имени Сакена Сейфуллина',
                'description1' => 'Казахский Агротехнический Университет имени Сакена Сейфуллина - Один из ведущих аграрных вузов Казахстана, готовящий специалистов в области сельского хозяйства, инженерии и экологии. Университет активно внедряет инновации в агропромышленный сектор.',
                'description2' => 'Университет имени Сакена Сейфуллина является центром научных исследований в области агротехнологий, устойчивого развития сельского хозяйства и цифровизации агропромышленного комплекса.',
                'description3' => 'Благодаря международному сотрудничеству, университет предлагает студентам возможность участия в обменных программах, стажировках и исследованиях в ведущих мировых аграрных институтах.',
                'location' => 'Астана, Казахстан',
                'email'=> 'office@kazatu.edu.kz',
                'password' => Hash::make('password123'),
                'verified' => 'accepted',
                'phone'=> '8 (7172) 31 75 47',
                'website' => 'https://kazatu.edu.kz',
                'created_at' => Carbon::now()->subDays(rand(1, 60)),
                'updated_at' => Carbon::now()->subDays(rand(1, 60)),
                'logo_url'=> 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIABoDDVzff-O4vjpRXOTkk8Q9nN-y0aT_nf0xXs08AJt6E9daI4A1-Dgs6XA071at12w&usqp=CAU',
                'photo_url' => 'https://univery.kz/images/agrarnyj-universitet-nur-sultan.jpg',
                'grants' => '1',
                'dormitory'=>'1',
                'address'=> 'просп. Женис 62, Астана Казахстан',
                'latitude' => '51.187320363531555',
                'longitude' => '71.40905965472486',
            ],
            [
                'name' => 'Медицинский Университет Астана',
                'description1' => 'Крупный медицинский вуз, специализирующийся на подготовке высококвалифицированных врачей, медсестер и научных работников в области здравоохранения.',
                'description2' => 'Университет активно внедряет современные медицинские технологии, симуляционное обучение и телемедицину, обеспечивая студентам передовую практическую подготовку.',
                'description3' => 'МУА сотрудничает с ведущими клиниками Казахстана и зарубежными медицинскими центрами, предоставляя студентам возможность прохождения практики и научных исследований на международном уровне.',
                'location' => 'Астана, Казахстан',
                'email'=> 'abiturient@amu.kz',
                'password' => Hash::make('password123'),
                'phone'=> '8 (7172) 53 95 12',
                'verified' => 'accepted',
                'website' => 'https://amu.edu.kz',
                'created_at' => Carbon::now()->subDays(rand(1, 60)),
                'updated_at' => Carbon::now()->subDays(rand(1, 60)),
                'logo_url'=> 'https://lms.amu.kz/theme/moove/pix/newlogo.png',
                'photo_url' => 'https://smapse.ru/storage/2020/03/astana-medical-university-smapse1.jpg',
                'grants' => '1',
                'dormitory'=>'0',
                'address'=> 'улица Бейбитшилик 49/A, Астана Казахстан',
                'latitude' => '51.18177110513288',
                'longitude' => '71.41642239705278',
            ],
            [
                'name' => 'Казахстанский Университет Экономики, Финансов и Международной Торговли',
                'description1' => 'Ведущий вуз в области экономики и финансов, готовящий специалистов по международной торговле, бухгалтерскому учету, налогообложению и бизнес-менеджменту.',
                'description2' => 'Университет предлагает образовательные программы, соответствующие мировым стандартам, и активно сотрудничает с международными финансовыми организациями.',
                'description3' => 'Вуз уделяет особое внимание подготовке кадров для государственных и частных структур, формируя лидеров в сфере экономики и международной торговли.',
                'location' => 'Астана, Казахстан',
                'email'=> 'mailbox@kuef.kz',
              'password' => Hash::make('password123'),
                'phone'=> '+7 (7172) 37-39-05',
                'verified' => 'accepted',
                'website' => 'https://kuef.kz',
                'created_at' => Carbon::now()->subDays(rand(1, 60)),
                'updated_at' => Carbon::now()->subDays(rand(1, 60)),
                'logo_url'=> 'https://d3hu5weehyyu21.cloudfront.net/images/university/id1359.jpg',
                'photo_url' => 'https://s.zagranitsa.com/images/guides/19694/original/c8c5dc096afe3771bb7a0248fc855982.jpg?1440153670',
                'grants' => '0',
                'dormitory'=>'1',
                'address'=> 'ул. Алпамыс батыр 7, Астана Казахстан',
                'latitude' => '51.14383838924555',
                'longitude' => '71.4274287111098',
            ],
            [
                'name' => 'Академия Государственного Управления при Президенте Республики Казахстан',
                'description1' => 'Академия является главным учебным центром страны по подготовке государственных служащих, ориентированных на эффективное управление и развитие государственных институтов.',
                'description2' => 'Учебные программы Академии разработаны с учетом международных стандартов и опыта ведущих управленческих школ мира.',
                'description3' => 'Академия активно взаимодействует с госорганами, бизнесом и международными партнерами, обеспечивая подготовку лидеров нового поколения в сфере госуправления.',
                'location' => 'Астана, Казахстан',
                'email'=> 'admission@apa.kz',
                'password' => Hash::make('password123'),
                'phone'=> '+7 (7172) 75 32 68',
                'website' => 'https://pa-academy.kz',
                'verified' => 'accepted',
                'created_at' => Carbon::now()->subDays(rand(1, 60)),
                'updated_at' => Carbon::now()->subDays(rand(1, 60)),
                'logo_url'=> 'https://admin.vipusknik.kz/storage/2011/unnamedjpg.jpeg',
                'photo_url' => 'https://liter.kz/cache/imagine/1200/uploads/news/2023/10/26/653a559dd5902266308527.jpeg',
                'grants' => '0',
                'dormitory'=>'0',
                'address'=> 'пр-т. Абая 33 а, Астана Казахстан',
                'latitude' => '51.16833248209512',
                'longitude' => '71.42026384123116',
            ],
            [
                'name' => 'Университет КАЗГЮУ',
                'description1' => 'Один из лучших юридических вузов Казахстана, известный высоким уровнем подготовки специалистов в области права, международных отношений и бизнеса.',
                'description2' => 'Университет сотрудничает с ведущими мировыми образовательными учреждениями, предоставляя студентам доступ к лучшим мировым практикам в области юриспруденции.',
                'description3' => 'КАЗГЮУ отличается высоким уровнем трудоустройства выпускников и тесными связями с юридическими фирмами, госструктурами и международными организациями.',
                'location' => 'Астана, Казахстан',
                'email'=> 'info@mnu.kz',
                'password' => Hash::make('password123'),
                'verified' => 'accepted',   
                'phone'=> '8 (7172) 70 30 30',
                'website' => 'https://kazguu.kz',
                'created_at' => Carbon::now()->subDays(rand(1, 60)),
                'updated_at' => Carbon::now()->subDays(rand(1, 60)),
                'logo_url'=> 'https://pbs.twimg.com/profile_images/451921663014080513/72rMZGQ7_200x200.png',
                'photo_url' => 'https://admin.vipusknik.kz/storage/3776/snimok-2png.png',
                'grants' => '1',
                'dormitory'=>'1',
                'address'=> 'Кургальжинское ш. 8, Астана Казахстан',
                'latitude' => '51.14838934409969',
                'longitude' => '71.37944445287141',
            ],
            [
                'name' => 'Международный Университет Астаны',
                'description1' => 'Университет ориентирован на подготовку специалистов международного уровня в различных сферах науки, техники и бизнеса.',
                'description2' => 'Вуз активно участвует в международных образовательных проектах и обменах, давая студентам возможность обучения за рубежом.',
                'description3' => 'Международный Университет Астаны развивает междисциплинарные исследования, привлекая ведущих специалистов и профессоров со всего мира.',
                'location' => 'Астана, Казахстан',
                'email'=> 'info@aiu.edu.kz',
                'password' => Hash::make('password123'),
                'phone'=> '8 (7172) 47 66 77',
                'verified' => 'accepted',
                'website' => 'https://mui.kz',
                'created_at' => Carbon::now()->subDays(rand(1, 60)),
                'updated_at' => Carbon::now()->subDays(rand(1, 60)),
                'logo_url'=> 'https://aiu.kz/media/news/2024/04/24/cp_aiu-logo.jpg',
                'photo_url' => 'https://aiu.kz/media/photos/2022/03/04/1H7A7990_1-min.jpg',
                'grants' => '1',
                'dormitory'=>'0',
                'address'=> 'просп. Кабанбай Батыра 8, Астана Казахстан',
                'latitude' => '51.144843187440536',
                'longitude' => '71.42293361979759',
            ],
            [
                'name' => 'Астана IT Университет',
                'description1' => 'Астана IT Университет это специализированный вуз, занимающийся подготовкой ИТ-специалистов, разработчиков программного обеспечения, кибербезопасников и инженеров данных.',
                'description2' => 'Университет тесно сотрудничает с технологическими компаниями и стартапами, предоставляя студентам возможность прохождения практики и трудоустройства в ведущих ИТ-компаниях.',
                'description3' => 'Астана IT Университет внедряет передовые методы обучения, включая онлайн-курсы, VR-технологии и искусственный интеллект.',
                'location' => 'Астана, Казахстан',
                'email'=> 'astanait@mail.ru',
                'password' => Hash::make('password123'),
                'verified' => 'accepted',
                'phone'=> '+7 (7172) 64‒57‒17',
                'website' => 'https://astanait.edu.kz',
                'created_at' => Carbon::now()->subDays(rand(1, 60)),
                'updated_at' => Carbon::now()->subDays(rand(1, 60)),
                'logo_url'=> 'https://static.tildacdn.com/tild3764-6633-4663-b138-303730646233/aitu-logo__2.png',
                'photo_url' => 'https://egemen.kz/media/2022/04/11/it-1.jpg',
                'grants' => '1',
                'dormitory'=>'0',
                'address'=> 'пр-т. Мангилик Ел., Астана Казахстан',
                'latitude' => '51.0909014744094',
                'longitude' => '71.41817088025934',
            ],
            [
                'name' => 'Казахстанский Университет Технологии и Бизнеса',
                'description1' => 'Университет готовит специалистов в области информационных технологий, инженерии и управления бизнесом, ориентируясь на современные рыночные требования.',
                'description2' => 'Вуз активно внедряет практико-ориентированные образовательные программы, сотрудничая с крупнейшими предприятиями Казахстана.',
                'description3' => 'Особое внимание в университете уделяется цифровым технологиям, логистике и инновационному бизнес-управлению.',
                'location' => 'Астана, Казахстан',
                'email'=> 'akutb@mail.ru',
                'verified' => 'accepted',
                'password' => Hash::make('password123'),
                'phone'=> '8 (7172) 72-58-15',
                'website' => 'https://kutb.kz',
                'created_at' => Carbon::now()->subDays(rand(1, 60)),
                'updated_at' => Carbon::now()->subDays(rand(1, 60)),
                'logo_url'=> 'https://www.kaztbu.edu.kz/storage/app/uploads/public/625/ce0/9fc/625ce09fcd332361771809.png',
                'photo_url' => 'https://testing.kz/images/universites/47/8b79dfe87b173466eb0a19c9ebf60b02.jpg',
                'grants' => '1',
                'dormitory'=>'1',
                'address'=> 'улица Кайыма Мухамедханов 37А, Астана Казахстан',
                'latitude' => '51.14482675669144',
                'longitude' => '71.36904055842398',
            ],
            [
                'name' => 'Университет «Туран-Астана»',
                'description1' => 'Университет специализируется на подготовке кадров в сфере бизнеса, туризма, медиа, маркетинга и менеджмента.',
                'description2' => '«Туран-Астана» активно развивает программы двойных дипломов и международные стажировки.',
                'description3' => 'Вуз ориентирован на практическое обучение, сотрудничая с ведущими казахстанскими и международными компаниями.',
                'location' => 'Астана, Казахстан',
                'email'=> 'admissions@tau-edu.kz',
                'password' => Hash::make('password123'),
                'phone'=> '8 (7172) 64 43 11',
                'verified' => 'accepted',
                'website' => 'tau-edu.kz',
                'created_at' => Carbon::now()->subDays(rand(1, 60)),
                'updated_at' => Carbon::now()->subDays(rand(1, 60)),
                'logo_url'=> 'https://tau-edu.kz/media/logo.png',
                'photo_url' => 'https://admin.vipusknik.kz/storage/1883/xxljpg.jpeg',
                'grants' => '1',
                'dormitory'=>'1',
                'address'=> 'ул. Ыкылас Дукенулы 29, Астана Казахстан',
                'latitude' => '51.18187767784688',
                'longitude' => '71.43151375233754',
            ],
            [
                'name' => 'Казахский национальный университет искусств',
                'description1' => 'Ведущий вуз страны по подготовке специалистов в области музыки, театра, изобразительного искусства и кинематографии.',
                'description2' => 'Университет предоставляет студентам возможность обучаться у известных мастеров искусства и участвовать в международных конкурсах.',
                'description3' => 'КазНУИ является центром культурных инициатив, объединяя творчество, научные исследования и современные технологии.',
                'location' => 'Астана, Казахстан',
                'email'=> 'Kaznui.priem@gmail.com',
               'password' => Hash::make('password123'),
                'verified' => 'accepted',
                'phone'=> '8 (7172) 70 55 35',
                'website' => 'kaznui.edu.kz',
                'created_at' => Carbon::now()->subDays(rand(1, 60)),
                'updated_at' => Carbon::now()->subDays(rand(1, 60)),
                'logo_url'=> 'https://cdn.etalapker.kz/public/media/1000094/logo/1706889381861_01ab82fe-4572-4ae9-8a96-ebbee11f31c3.png',
                'photo_url' => 'https://univery.kz/images/kazakhskij-natsionalnyj-universitet-iskusstv.jpg',
                'grants' => '1',
                'dormitory'=>'1',
                'address'=> '“Шабыт” шығармашылық сарайы, Тәуелсіздік даңғылы 50, Астана Казахстан',
                'latitude' => '51.12292699002619',
                'longitude' => '71.47330237457513',
            ],
            [
                'name' => 'Казахская национальная академия хореографии',
                'description1' => 'Первый в Центральной Азии вуз, специализирующийся на подготовке профессиональных артистов балета, хореографов и педагогов.',
                'description2' => 'Академия обучает студентов по международным стандартам, предоставляя возможность стажировок в ведущих мировых балетных театрах.',
                'description3' => 'В стенах академии сочетаются традиционные казахские танцы и современные хореографические тенденции.',
                'location' => 'Астана, Казахстан',
                'email'=> 'info@balletacademy.kz',
               'password' => Hash::make('password123'),
                'verified' => 'accepted',
                'phone'=> '+7 (7172) 79‒85‒70',
                'website' => 'balletacademy.kz',
                'created_at' => Carbon::now()->subDays(rand(1, 60)),
                'updated_at' => Carbon::now()->subDays(rand(1, 60)),
                'logo_url'=> 'https://astana.hh.kz/employer-logo/3026949.jpeg',
                'photo_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRANDUluwQho_km2oa9MTwBh3zDvRi92Q_KfQ&s',
                'grants' => '1',
                'dormitory'=>'0',
                'address'=> 'Uly Dala Avenue 43/1, Астана Казахстан',
                'latitude' => '51.09906938290285',
                'longitude' => '71.42029580391535',
            ],
            [
                'name' => 'Карагандинский университет Казпотребсоюза, филиал в г. Астана',
                'description1' => 'Филиал ведущего экономического университета Казахстана, готовящий специалистов в области менеджмента, маркетинга, финансов и бухгалтерского учета.',
                'description2' => 'Университет предлагает программы, ориентированные на развитие малого и среднего бизнеса, а также государственных структур.',
                'description3' => 'Образование в вузе сочетается с исследовательской работой и практическими проектами в сфере экономики и предпринимательства.',
                'location' => 'Астана, Казахстан',
                'email'=> '+7 (7172) 50‒18‒31',
                'phone'=> 'keu@mail.ru',
                'verified' => 'accepted',
               'password' => Hash::make('password123'),
                'website' => 'www.keu.kz',
                'created_at' => Carbon::now()->subDays(rand(1, 60)),
                'updated_at' => Carbon::now()->subDays(rand(1, 60)),
                'logo_url'=> 'https://admin.vipusknik.kz/storage/1798/ku4png.png',
                'photo_url' => 'https://admin.vipusknik.kz/storage/1944/keuk-astanajpg.jpeg',
                'grants' => '1',
                'dormitory'=>'1',
                'address'=> 'ул. Кенесары 60, Астана Казахстан',
                'latitude' => '51.16678578501739',
                'longitude' => '71.44970622262002',
            ],
            [
                'name' => 'Казахстанский филиал МГУ им. М.В.Ломоносова',
                'description1' => 'Филиал одного из лучших университетов мира, предоставляющий образование мирового уровня в различных дисциплинах.',
                'description2' => 'Программы обучения соответствуют стандартам Московского государственного университета, что обеспечивает высокий уровень подготовки специалистов.',
                'description3' => 'Выпускники филиала востребованы как в Казахстане, так и за рубежом, благодаря признанному международному диплому МГУ.',
                'location' => 'Астана, Казахстан',
                'email'=> 'otvet@msu.kz',
                'password' => Hash::make('password123'),
                'phone'=> '8 (7172) 35 43 87',
                'verified' => 'accepted',
                'website' => 'www.msu.kz',
                'created_at' => Carbon::now()->subDays(rand(1, 60)),
                'updated_at' => Carbon::now()->subDays(rand(1, 60)),
                'logo_url'=> 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIzwet3YlYaNt21kKDjkoo-gDIdTahzq8glA&s',
                'photo_url' => 'https://kzkazan.ru/wp-content/uploads/2019/04/img_3029_3535.jpg',
                'grants' => '1',
                'dormitory'=>'1',
                'address'=> 'ул. Кажымукан Муңайтпасов 11, Астана Казахстан',
                'latitude' => '51.15580967173556',
                'longitude' => '71.46936824678323',
            ],
            [
                'name' => 'Национальный университет обороны Республики Казахстан',
                'description1' => 'Главный военный вуз страны, осуществляющий подготовку офицеров и руководящих кадров Вооруженных Сил Казахстана.',
                'description2' => 'Университет проводит обучение на основе современных стратегий национальной безопасности и военной науки.',
                'description3' => 'Преподавательский состав включает ведущих военных экспертов и специалистов по обороне.',
                'location' => 'Астана, Казахстан',
                'email'=> '',
              'password' => Hash::make('password123'),
                'phone'=> '',
                'website' => 'https://www.apa.kz/ru/',
                'created_at' => Carbon::now()->subDays(rand(1, 60)),
                'updated_at' => Carbon::now()->subDays(rand(1, 60)),
                'logo_url'=> 'https://upload.wikimedia.org/wikipedia/commons/5/52/%D0%AD%D0%BC%D0%B1%D0%BB%D0%B5%D0%BC%D0%B0_%D0%9D%D0%A3%D0%9E_%D0%A0%D0%9A.jpg',
                'photo_url' => 'https://baigenews.kz/storage/storage/news/2022/05/06/mainphoto/1858/1200x700_aP7s0AnMkJPu9A7zYy2IJRIzOE67rDG2ngfCqwta.jpg',
                'grants' => '1',
                'dormitory'=>'1',
                'address'=> 'просп. Туран 72, Астана Казахстан',
                'verified' => 'accepted',
                'latitude' => '51.07811573883253',
                'longitude' => '71.39173236635943',
            ],
            [
                'name' => 'Esil University',
                'description1' => 'Университет специализируется на обучении в сферах экономики, финансов, менеджмента и цифровых технологий.',
                'description2' => 'Вуз предлагает программы бакалавриата и магистратуры, ориентированные на развитие профессиональных навыков.',
                'description3' => 'Esil University активно сотрудничает с международными компаниями и академическими учреждениями.',
                'location' => 'Астана, Казахстан',
                'email'=> 'nuo@mail.ru',
                'password' => Hash::make('password123'),
                'phone'=> '+7 (7172) 26‒36‒79',
                'website' => 'nuo.kz',
                'created_at' => Carbon::now()->subDays(rand(1, 60)),
                'updated_at' => Carbon::now()->subDays(rand(1, 60)),
                'logo_url'=> 'https://esil.edu.kz/wp-content/uploads/2023/08/logo-esu.png',
                'photo_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaX9CWJyj92lcfzHqrH64knNKwTmtW-H7Etw&s',
                'grants' => '1',
                'dormitory'=>'1',
                'verified' => 'accepted',
                'address'=> 'Ахмет Жұбанов көшесі 7, Астана Казахстан',
                'latitude' => '51.16010074294173',
                'longitude' => '71.45801244678344',
            ],
            [
                'name' => 'Евразийский гуманитарный институт имени А. Кусаинова',
                'description1' => 'Университет специализируется на подготовке специалистов в области права, педагогики, психологии и международных отношений.',
                'description2' => 'Вуз предлагает инновационные образовательные программы с учетом современных требований рынка труда.',
                'description3' => 'ЕГИ активно участвует в научных исследованиях и международных образовательных проектах.',
                'location' => 'Астана, Казахстан',
                'email'=> 'eagi_pk@egi.edu.kz',
                'password' => Hash::make('password123'),
                'phone'=> '8 (7172) 56 22 00',
                'website' => 'egi.edu.kz',
                'verified' => 'accepted',
                'created_at' => Carbon::now()->subDays(rand(1, 60)),
                'updated_at' => Carbon::now()->subDays(rand(1, 60)),
                'logo_url'=> 'https://egi.kz/wp-content/uploads/2016/10/logo.jpg',
                'photo_url' => 'https://keagi.edu.kz/2020/wp-content/uploads/slider3/_2020-05_1_1920x800.jpeg',
                'grants' => '1',
                'dormitory'=>'1',
                'address'=> 'проспект Магжана Жумабаева 4/1, Астана Казахстан',
                'latitude' => '51.15568542902447',
                'longitude' => '71.47947961467557',
            ],
        ]);


    }
}
