<?php

namespace Database\Seeders;


use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SpecialtiesSeeder extends Seeder
{
    public function run()
    {
        $specialties = [
            // 6B01 Педагогические науки
            ['name' => 'Дошкольное образование', 'qualification_id'  => 1],
            ['name' => 'Дошкольное обучение и воспитание', 'qualification_id' => 1],

            ['name' => 'Педагогика и психология', 'qualification_id' => 2],
            ['name' => 'Психология и менеджмент образования', 'qualification_id' => 2],

            ['name' => 'Социальная и ювенальная педагогика', 'qualification_id' => 3],
            ['name' => 'Социальная педагогика и самопознание', 'qualification_id' => 3],

            ['name' => 'Дефектология', 'qualification_id' => 4],
            ['name' => 'Логопедия', 'qualification_id' => 4],
            ['name' => 'Специальная педагогика', 'qualification_id' => 4],
            ['name' => 'Сурдопедагогика', 'qualification_id' => 4],
            ['name' => 'Тьюторство в инклюзивном образовании', 'qualification_id' => 4],

            ['name' => 'Начальное образование', 'qualification_id' => 5],
            ['name' => 'Педагогика и методика начального обучения', 'qualification_id' => 5],

            ['name' => 'Музыкальное образование', 'qualification_id' => 6],

            ['name' => 'История', 'qualification_id' => 7],
            ['name' => 'История и обществознание (IP)', 'qualification_id' => 7],
            ['name' => 'История и религиоведение', 'qualification_id' => 7],
            ['name' => 'История и цифровая гуманитаристика', 'qualification_id' => 7],

            ['name' => 'Биология', 'qualification_id' => 8],
            ['name' => 'Биология-Естествознание', 'qualification_id' => 8],
            ['name' => 'География', 'qualification_id' => 8],
            ['name' => 'География-История', 'qualification_id' => 8],
            ['name' => 'Информатика', 'qualification_id' => 8],
            ['name' => 'Информатика и робототехника', 'qualification_id' => 8],
            ['name' => 'Кибер-Математика', 'qualification_id' => 8],
            ['name' => 'Математика', 'qualification_id' => 8],
            ['name' => 'Физика', 'qualification_id' => 8],
            ['name' => 'Химия', 'qualification_id' => 8],

            ['name' => 'Английский язык (IP)', 'qualification_id' => 9],
            ['name' => 'Иностранный язык: два иностранных языка', 'qualification_id' => 9],
            ['name' => 'Казахский язык и литература', 'qualification_id' => 9],
            ['name' => 'Казахский язык и литература – английский язык', 'qualification_id' => 9],
            ['name' => 'Казахский язык и литература в учреждениях образования с казахским и русским языком обучения', 'qualification_id' => 9],
            ['name' => 'Казахский язык и литература в школах с неказахским языком обучения', 'qualification_id' => 9],
            ['name' => 'Казахский, русский языки и литература', 'qualification_id' => 9],
            ['name' => 'Русский язык и литература', 'qualification_id' => 9],
            ['name' => 'Русский язык и литература в школах с нерусским языком обучения', 'qualification_id' => 9],
            ['name' => 'Русский язык и литература в школах с русским и нерусским языками обучения (IP)', 'qualification_id' => 9],
            ['name' => 'Узбекский язык и литература', 'qualification_id' => 9],
            ['name' => 'Учитель английского и русского языков', 'qualification_id' => 9],
            ['name' => 'Учитель английского языка и начальных классов', 'qualification_id' => 9],

            ['name' => 'Арт-образование и предпринимательство', 'qualification_id' => 10],
            ['name' => 'Визуальное искусство, художественный труд, графика и проектирование', 'qualification_id' => 10],
            ['name' => 'Изобразительное искусство и черчение', 'qualification_id' => 10],
            ['name' => 'Изобразительное искусство, художественный труд и графика', 'qualification_id' => 10],
            ['name' => 'Начальная военная подготовка', 'qualification_id' => 10],
            ['name' => 'Оздоровительная физическая культура', 'qualification_id' => 10],
            ['name' => 'Основы права и экономики', 'qualification_id' => 10],
            ['name' => 'Профессиональное обучение', 'qualification_id' => 10],
            ['name' => 'Профессиональное обучение, художественный труд и графика', 'qualification_id' => 10],
            ['name' => 'Трудовое обучение и основы предпринимательства (IP)', 'qualification_id' => 10],
            ['name' => 'Учитель художественного труда и изобразительного искусства', 'qualification_id' => 10],
            ['name' => 'Физическая культура и начальная военная подготовка', 'qualification_id' => 10],
            ['name' => 'Физическая культура и спорт', 'qualification_id' => 10],
            ['name' => 'Художественное образование (IP)', 'qualification_id' => 10],



            // 6B02 Искусство и гуманитарные науки
            ['name' => 'Операторское искусство', 'qualification_id' => 11],

            ['name' => 'Археология и этнология', 'qualification_id' => 12],
            ['name' => 'Востоковедение', 'qualification_id' => 12],
            ['name' => 'Исламоведение', 'qualification_id' => 12],
            ['name' => 'История', 'qualification_id' => 12],
            ['name' => 'Музейное дело и охрана памятников', 'qualification_id' => 12],
            ['name' => 'Научная история', 'qualification_id' => 12],
            ['name' => 'Религиоведение', 'qualification_id' => 12],
            ['name' => 'Религиоведение и философия', 'qualification_id' => 12],
            ['name' => 'Теология', 'qualification_id' => 12],
            ['name' => 'Тюркология', 'qualification_id' => 12],
            ['name' => 'Философия', 'qualification_id' => 12],

            ['name' => 'Оркестровое дирижирование', 'qualification_id' => 13],
            ['name' => 'Хоровое дирижирование', 'qualification_id' => 13],

            ['name' => 'Creative artes', 'qualification_id' => 14],
            ['name' => 'Digital cultures', 'qualification_id' => 14],
            ['name' => 'Digital Filmmaking', 'qualification_id' => 14],
            ['name' => 'Web-дизайн', 'qualification_id' => 14],
            ['name' => 'Актерское искусство', 'qualification_id' => 14],
            ['name' => 'Арт-дизайн', 'qualification_id' => 14],
            ['name' => 'Арт-менеджмент', 'qualification_id' => 14],
            ['name' => 'Архитектурный дизайн', 'qualification_id' => 14],
            ['name' => 'Аудиопроизводство', 'qualification_id' => 14],
            ['name' => 'Вокальное искусство', 'qualification_id' => 14],
            ['name' => 'Графика', 'qualification_id' => 14],
            ['name' => 'Графический дизайн', 'qualification_id' => 14],
            ['name' => 'Графический дизайн (иллюстрация)', 'qualification_id' => 14],
            ['name' => 'Декоративно-прикладное искусство', 'qualification_id' => 14],
            ['name' => 'Декоративное искусство', 'qualification_id' => 14],
            ['name' => 'Декоративное искусство — художественная обработка дерева', 'qualification_id' => 14],
            ['name' => 'Декоративное искусство — художественная обработка металла и других материалов', 'qualification_id' => 14],
            ['name' => 'Декоративное искусство — художественное ткачество', 'qualification_id' => 14],
            ['name' => 'Декоративное искусство и этнодизайн', 'qualification_id' => 14],
            ['name' => 'Дизайн', 'qualification_id' => 14],
            ['name' => 'Дизайн интерьера', 'qualification_id' => 14],
            ['name' => 'Дизайн моды', 'qualification_id' => 14],
            ['name' => 'Дизайн среды', 'qualification_id' => 14],
            ['name' => 'Дирижирование', 'qualification_id' => 14],
            ['name' => 'Живопись', 'qualification_id' => 14],
            ['name' => 'Живопись — Монументальная живопись', 'qualification_id' => 14],
            ['name' => 'Живопись — Реставрация', 'qualification_id' => 14],
            ['name' => 'Живопись — Станковая живопись', 'qualification_id' => 14],
            ['name' => 'Издательское дело', 'qualification_id' => 14],
            ['name' => 'Инструментальное искусство', 'qualification_id' => 14],
            ['name' => 'Инструментальное исполнительство — Духовые и ударные инструменты', 'qualification_id' => 14],
            ['name' => 'Инструментальное исполнительство — Струнные инструменты-АВАК', 'qualification_id' => 14],
            ['name' => 'Инструментальное исполнительство — Струнные инструменты-Скрипка', 'qualification_id' => 14],
            ['name' => 'Инструментальное исполнительство — Фортепиано', 'qualification_id' => 14],
            ['name' => 'Искусство эстрады', 'qualification_id' => 14],
            ['name' => 'Искусство эстрады — Артист эстрадного оркестра', 'qualification_id' => 14],
            ['name' => 'Искусство эстрады — Вокалист эстрады', 'qualification_id' => 14],
            ['name' => 'Искусство эстрады — Композитор эстрады, аранжировщик', 'qualification_id' => 14],
            ['name' => 'Искусствоведение', 'qualification_id' => 14],
            ['name' => 'Композиция', 'qualification_id' => 14],
            ['name' => 'Народные инструменты (Домбыра)', 'qualification_id' => 14],
            ['name' => 'Народные инструменты (Қобыз и РНИ)', 'qualification_id' => 14],
            ['name' => 'Полиграфия', 'qualification_id' => 14],
            ['name' => 'Поэзия и искусство', 'qualification_id' => 14],
            ['name' => 'Продюсирование кино и ТВ', 'qualification_id' => 14],
            ['name' => 'Промышленный дизайн', 'qualification_id' => 14],
            ['name' => 'Режиссура', 'qualification_id' => 14],
            ['name' => 'Сервис в индустрии моды и красоты', 'qualification_id' => 14],
            ['name' => 'Скульптура', 'qualification_id' => 14],
            ['name' => 'Сценография', 'qualification_id' => 14],
            ['name' => 'Сценография — Дизайн одежды', 'qualification_id' => 14],
            ['name' => 'Сценография — Светотехника', 'qualification_id' => 14],
            ['name' => 'Сценография — Сценография костюма театра, кино и ТВ', 'qualification_id' => 14],
            ['name' => 'Сценография — Театральная техника и оформление спектакля', 'qualification_id' => 14],
            ['name' => 'Сценография — Театрально-декорационное искусство', 'qualification_id' => 14],
            ['name' => 'Сценография грима театра, кино и ТВ', 'qualification_id' => 14],
            ['name' => 'Традиционное музыкальное искусство', 'qualification_id' => 14],
            ['name' => 'Традиционное пение', 'qualification_id' => 14],
            ['name' => 'Традиционный жыр', 'qualification_id' => 14],
            ['name' => 'Традиционный жыр (Айтыс)', 'qualification_id' => 14],
            ['name' => 'Хореография', 'qualification_id' => 14],
            ['name' => 'Художник кино и ТВ', 'qualification_id' => 14],

            ['name' => 'Искусствоведение', 'qualification_id' => 15],
            ['name' => 'Киноведение', 'qualification_id' => 15],
            ['name' => 'Кинотеледраматургия', 'qualification_id' => 15],
            ['name' => 'Музееведение', 'qualification_id' => 15],
            ['name' => 'Театроведение', 'qualification_id' => 15],

            ['name' => 'Композиция', 'qualification_id' => 16],

            ['name' => 'Музыковедение', 'qualification_id' => 17],

            ['name' => 'Режиссура игрового кино', 'qualification_id' => 18],
            ['name' => 'Режиссура телевидения', 'qualification_id' => 18],
            ['name' => 'Актёр кино', 'qualification_id' => 18],
            ['name' => 'Арт-менеджмент', 'qualification_id' => 18],
            ['name' => 'Звукорежиссура кино и ТВ', 'qualification_id' => 18],
            ['name' => 'Музыкальная звукорежиссура', 'qualification_id' => 18],
            ['name' => 'Режиссура анимационного фильма', 'qualification_id' => 18],
            ['name' => 'Режиссура документального кино', 'qualification_id' => 18],
            ['name' => 'Режиссура музыкального театра', 'qualification_id' => 18],
            ['name' => 'Режиссура, продюсерство кино и ТВ', 'qualification_id' => 18],

            ['name' => 'Артист драматического театра и кино', 'qualification_id' => 19],
            ['name' => 'Артист кукольного театра', 'qualification_id' => 19],
            ['name' => 'Артист музыкального театра', 'qualification_id' => 19],

            ['name' => 'Филология: казахская филология', 'qualification_id' => 20],
            ['name' => 'Филология: русская филология', 'qualification_id' => 20],
            ['name' => 'Иностранная филология', 'qualification_id' => 20],
            ['name' => 'Иностранная филология: узбекский язык', 'qualification_id' => 20],
            ['name' => 'Межкультурно-коммуникативный перевод', 'qualification_id' => 20],
            ['name' => 'Перевод и переводоведение', 'qualification_id' => 20],
            ['name' => 'Переводческое дело', 'qualification_id' => 20],
            ['name' => 'Технический перевод', 'qualification_id' => 20],
            ['name' => 'Цифровая лингвистика', 'qualification_id' => 20],






            // 6B03 Социальные науки, журналистика и информация
            ['name' => 'Digital Journalism (Цифровая журналистика)', 'qualification_id' => 21],
            ['name' => 'New media', 'qualification_id' => 21],
            ['name' => 'PR и Реклама', 'qualification_id' => 21],
            ['name' => 'PR-журналистика', 'qualification_id' => 21],
            ['name' => 'Архивоведение и библиотечно-информационная деятельность', 'qualification_id' => 21],
            ['name' => 'Архивоведение, документоведение и документационное обеспечение', 'qualification_id' => 21],
            ['name' => 'Библиотечно-педагогическая деятельность', 'qualification_id' => 21],
            ['name' => 'Библиотечное дело', 'qualification_id' => 21],
            ['name' => 'Библиотечные информационные системы', 'qualification_id' => 21],
            ['name' => 'Бизнес-журналистика, SMM & PR', 'qualification_id' => 21],
            ['name' => 'Журналистика', 'qualification_id' => 21],
            ['name' => 'Конвергентная журналистика', 'qualification_id' => 21],
            ['name' => 'Международная журналистика и интернет-безопасность', 'qualification_id' => 21],
            ['name' => 'Связь с общественностью', 'qualification_id' => 21],
            ['name' => 'Телерадиожурналистика', 'qualification_id' => 21],

            ['name' => 'Клиническая психология', 'qualification_id' => 22],
            ['name' => 'Культурология', 'qualification_id' => 22],
            ['name' => 'Международная аналитика', 'qualification_id' => 22],
            ['name' => 'Международные отношения', 'qualification_id' => 22],
            ['name' => 'Организационная психология', 'qualification_id' => 22],
            ['name' => 'Политические массовые коммуникации', 'qualification_id' => 22],
            ['name' => 'Политология', 'qualification_id' => 22],
            ['name' => 'Психологические особенности развития личности', 'qualification_id' => 22],
            ['name' => 'Психологическое консультирование', 'qualification_id' => 22],
            ['name' => 'Психология', 'qualification_id' => 22],
            ['name' => 'Психология и менеджмент в образовании', 'qualification_id' => 22],
            ['name' => 'Регионоведение', 'qualification_id' => 22],
            ['name' => 'Социология', 'qualification_id' => 22],
            ['name' => 'Управление социально-психологическими процессами', 'qualification_id' => 22],



            // 6B04 Бизнес, управление и право
            ['name' => 'BBA in Accounting', 'qualification_id' => 23],
            ['name' => 'BBA in Accounting (2 года)', 'qualification_id' => 23],
            ['name' => 'BBA in Accounting (3 года)', 'qualification_id' => 23],
            ['name' => 'BBA in Business Economics', 'qualification_id' => 23],
            ['name' => 'BBA in Business Economics (2 года)', 'qualification_id' => 23],
            ['name' => 'BBA in Business Economics (3 года)', 'qualification_id' => 23],
            ['name' => 'BBA in Finance', 'qualification_id' => 23],
            ['name' => 'BBA in Finance (2 года)', 'qualification_id' => 23],
            ['name' => 'BBA in Finance (3 года)', 'qualification_id' => 23],
            ['name' => 'BBA in Financial Risk Management', 'qualification_id' => 23],
            ['name' => 'BBA in HR and Business Planning', 'qualification_id' => 23],
            ['name' => 'BBA in Management', 'qualification_id' => 23],
            ['name' => 'BBA in Management (2 года)', 'qualification_id' => 23],
            ['name' => 'BBA in Management (3 года)', 'qualification_id' => 23],
            ['name' => 'BBA in Marketing', 'qualification_id' => 23],
            ['name' => 'BBA in Marketing (2 года)', 'qualification_id' => 23],
            ['name' => 'Business Administration in Entrepreneurship', 'qualification_id' => 23],
            ['name' => 'Business Management', 'qualification_id' => 23],
            ['name' => 'Digital маркетинг', 'qualification_id' => 23],
            ['name' => 'Digital-бизнес', 'qualification_id' => 23],
            ['name' => 'EVENT-менеджмент', 'qualification_id' => 23],
            ['name' => 'Global Management', 'qualification_id' => 23],
            ['name' => 'HR и бизнес-планирование', 'qualification_id' => 23],
            ['name' => 'HR-менеджмент', 'qualification_id' => 23],
            ['name' => 'International Trade', 'qualification_id' => 23],
            ['name' => 'IT-маркетинг', 'qualification_id' => 23],
            ['name' => 'IТ-менеджмент', 'qualification_id' => 23],
            ['name' => 'Product Manager', 'qualification_id' => 23],
            ['name' => 'Social медиа маркетинг', 'qualification_id' => 23],
            ['name' => 'Агротуризм', 'qualification_id' => 23],
            ['name' => 'Банковское дело', 'qualification_id' => 23],
            ['name' => 'Банковское дело и финансовый менеджмент', 'qualification_id' => 23],
            ['name' => 'Бизнес-администрирование', 'qualification_id' => 23],
            ['name' => 'Бизнес-администрирование (Двудипломная программа с UIBE)', 'qualification_id' => 23],
            ['name' => 'Бизнес-администрирование в области предпринимательства', 'qualification_id' => 23],
            ['name' => 'Бизнес-аналитика и экономика', 'qualification_id' => 23],
            ['name' => 'Бизнес-управление производственными системами', 'qualification_id' => 23],
            ['name' => 'Бизнес-финансы', 'qualification_id' => 23],
            ['name' => 'Бренд-менеджмент', 'qualification_id' => 23],
            ['name' => 'Бухгалтерский учет и экономический анализ', 'qualification_id' => 23],
            ['name' => 'Государственная служба и управление', 'qualification_id' => 23],
            ['name' => 'Государственное и местное управление', 'qualification_id' => 23],
            ['name' => 'Государственные финансы', 'qualification_id' => 23],
            ['name' => 'Государственный аудит', 'qualification_id' => 23],
            ['name' => 'Государственный менеджмент и e-government', 'qualification_id' => 23],
            ['name' => 'Государственный финансовый менеджмент', 'qualification_id' => 23],
            ['name' => 'Инновационная экономика', 'qualification_id' => 23],
            ['name' => 'Инновационный менеджмент', 'qualification_id' => 23],
            ['name' => 'Информационные и инновационные технологии в экономике', 'qualification_id' => 23],
            ['name' => 'Корпоративные финансы', 'qualification_id' => 23],
            ['name' => 'Маркетинг', 'qualification_id' => 23],
            ['name' => 'Маркетинг в цифровой экономике', 'qualification_id' => 23],
            ['name' => 'Маркетинг и PR-менеджмент', 'qualification_id' => 23],
            ['name' => 'Маркетинговые исследования и анализ', 'qualification_id' => 23],
            ['name' => 'Международная торговля и экономика (Двудипломная программа с UIBE)', 'qualification_id' => 23],
            ['name' => 'Международные отношения и экономика', 'qualification_id' => 23],
            ['name' => 'Международный бизнес', 'qualification_id' => 23],
            ['name' => 'Международный бизнес (Двудипломная программа с UIBE)', 'qualification_id' => 23],
            ['name' => 'Международный бизнес аграрными товарами', 'qualification_id' => 23],
            ['name' => 'Менеджмент', 'qualification_id' => 23],
            ['name' => 'Менеджмент / Business administration', 'qualification_id' => 23],
            ['name' => 'Менеджмент /Bachelor of Hotel Management', 'qualification_id' => 23],
            ['name' => 'Менеджмент в сетевом бизнесе', 'qualification_id' => 23],
            ['name' => 'Менеджмент гостеприимства', 'qualification_id' => 23],
            ['name' => 'Менеджмент и маркетинг', 'qualification_id' => 23],
            ['name' => 'Менеджмент онлайн-продаж', 'qualification_id' => 23],
            ['name' => 'Менеджмент предприятий', 'qualification_id' => 23],
            ['name' => 'Менеджмент спорта', 'qualification_id' => 23],
            ['name' => 'Менеджмент. Маркетинг. Продажи', 'qualification_id' => 23],
            ['name' => 'Мировая экономика', 'qualification_id' => 23],
            ['name' => 'Налоговый менеджмент', 'qualification_id' => 23],
            ['name' => 'Организация налогового учета и аудита в отраслях экономики', 'qualification_id' => 23],
            ['name' => 'Оценка (по отраслям)', 'qualification_id' => 23],
            ['name' => 'Предпринимательство', 'qualification_id' => 23],
            ['name' => 'Проектно-инновационный менеджмент', 'qualification_id' => 23],
            ['name' => 'Региональное развитие', 'qualification_id' => 23],
            ['name' => 'Таможенное дело (экономика)', 'qualification_id' => 23],
            ['name' => 'Управление и экономика промышленности', 'qualification_id' => 23],
            ['name' => 'Управление финансами наукоемких предприятий', 'qualification_id' => 23],
            ['name' => 'Урбанистика', 'qualification_id' => 23],
            ['name' => 'Учет и аудит', 'qualification_id' => 23],
            ['name' => 'Учет и аудит в промышленности', 'qualification_id' => 23],
            ['name' => 'Учет и аудит по программе ACCA', 'qualification_id' => 23],
            ['name' => 'Учет, анализ и аудит на предприятии', 'qualification_id' => 23],
            ['name' => 'Финансово-таможенный менеджмент', 'qualification_id' => 23],
            ['name' => 'Финансовые рынки и финансовые институты', 'qualification_id' => 23],
            ['name' => 'Финансовые технологии', 'qualification_id' => 23],
            ['name' => 'Финансовый инжиниринг', 'qualification_id' => 23],
            ['name' => 'Финансы', 'qualification_id' => 23],
            ['name' => 'Экономика', 'qualification_id' => 23],

            ['name' => 'Урбанистика и сити-менеджмент', 'qualification_id' => 24],

            ['name' => 'In-house юрист', 'qualification_id' => 25],
            ['name' => 'International law and security', 'qualification_id' => 25],
            ['name' => 'IT LAW', 'qualification_id' => 25],
            ['name' => 'IT-юрист', 'qualification_id' => 25],
            ['name' => 'Бизнес-право', 'qualification_id' => 25],
            ['name' => 'Государственная служба', 'qualification_id' => 25],
            ['name' => 'Гражданское право и гражданский процесс', 'qualification_id' => 25],
            ['name' => 'Корпоративное право', 'qualification_id' => 25],
            ['name' => 'Корпоративный юрист', 'qualification_id' => 25],
            ['name' => 'Международное право', 'qualification_id' => 25],
            ['name' => 'Международное право, юрист-международник со знанием двух иностранных языков', 'qualification_id' => 25],
            ['name' => 'Международное экономическое право', 'qualification_id' => 25],
            ['name' => 'Право', 'qualification_id' => 25],
            ['name' => 'Право зеленой экономики со знанием двух иностранных языков', 'qualification_id' => 25],
            ['name' => 'Право и государственное управление', 'qualification_id' => 25],
            ['name' => 'Право и правоохранительная деятельность', 'qualification_id' => 25],
            ['name' => 'Правовое обеспечение экономической безопасности', 'qualification_id' => 25],
            ['name' => 'Правовое обеспечение экономической деятельности', 'qualification_id' => 25],
            ['name' => 'Правовое регулирование экономики', 'qualification_id' => 25],
            ['name' => 'Правовое сопровождение бизнеса', 'qualification_id' => 25],
            ['name' => 'Правоохранительная и судебная деятельность', 'qualification_id' => 25],
            ['name' => 'Противодействие уголовным правонарушениям в сфере информзащиты', 'qualification_id' => 25],
            ['name' => 'Публичное право', 'qualification_id' => 25],
            ['name' => 'Социально-правовое партнерство', 'qualification_id' => 25],
            ['name' => 'Судебная и правоохранительная деятельность', 'qualification_id' => 25],
            ['name' => 'Судебно-правозащитная деятельность', 'qualification_id' => 25],
            ['name' => 'Судебно-прокурорская деятельность', 'qualification_id' => 25],
            ['name' => 'Таможенное дело', 'qualification_id' => 25],
            ['name' => 'Таможенное дело (право)', 'qualification_id' => 25],
            ['name' => 'Таможенное оформление и таможенный контроль', 'qualification_id' => 25],
            ['name' => 'Уголовное право и уголовный процесс', 'qualification_id' => 25],
            ['name' => 'Финансовое право', 'qualification_id' => 25],
            ['name' => 'Частное право', 'qualification_id' => 25],
            ['name' => 'Юридическое сопровождение предпринимательской деятельности', 'qualification_id' => 25],
            ['name' => 'Юриспруденция', 'qualification_id' => 25],
            ['name' => 'Юриспруденция (2 года)', 'qualification_id' => 25],
            ['name' => 'Юриспруденция (3 года)', 'qualification_id' => 25],





            // 6B05 Естественные науки, математика и статистика
            ['name' => 'Биоинженерия и биоинформатика', 'qualification_id' => 26],
            ['name' => 'Биологическая инженерия', 'qualification_id' => 26],
            ['name' => 'Биология', 'qualification_id' => 26],
            ['name' => 'Биомедицина', 'qualification_id' => 26],
            ['name' => 'Биотехнология', 'qualification_id' => 26],
            ['name' => 'Биофизика', 'qualification_id' => 26],
            ['name' => 'Генетика', 'qualification_id' => 26],
            ['name' => 'Геоботаника', 'qualification_id' => 26],
            ['name' => 'Ландшафтный дизайн', 'qualification_id' => 26],
            ['name' => 'Микробиология', 'qualification_id' => 26],

            ['name' => 'Applied mathematics in digital economy', 'qualification_id' => 27],
            ['name' => 'Statistics and data science', 'qualification_id' => 27],
            ['name' => 'Актуарная математика', 'qualification_id' => 27],
            ['name' => 'Математика', 'qualification_id' => 27],
            ['name' => 'Математическая экономика и анализ данных', 'qualification_id' => 27],
            ['name' => 'Механика', 'qualification_id' => 27],
            ['name' => 'Статистика', 'qualification_id' => 27],

            ['name' => 'География', 'qualification_id' => 28],
            ['name' => 'География и природопользование', 'qualification_id' => 28],
            ['name' => 'Гидрология', 'qualification_id' => 28],
            ['name' => 'Ландшафтное проектирование', 'qualification_id' => 28],
            ['name' => 'Метеорология', 'qualification_id' => 28],
            ['name' => 'Окружающая среда и устойчивое развитие', 'qualification_id' => 28],
            ['name' => 'Охрана окружающей среды и рациональное использование природных ресурсов', 'qualification_id' => 28],
            ['name' => 'Рекреационная география и туризм', 'qualification_id' => 28],
            ['name' => 'Экология', 'qualification_id' => 28],
            ['name' => 'Экология и природопользование', 'qualification_id' => 28],
            ['name' => 'Экотехнология и устойчивое развитие', 'qualification_id' => 28],

            ['name' => 'Астрономия и методы дистанционных исследований', 'qualification_id' => 29],
            ['name' => 'Инженерная физика и материаловедение', 'qualification_id' => 29],
            ['name' => 'Инженерная физика и технологии новых материалов', 'qualification_id' => 29],
            ['name' => 'Компьютерная физика', 'qualification_id' => 29],
            ['name' => 'Техническая физика', 'qualification_id' => 29],
            ['name' => 'Физика', 'qualification_id' => 29],
            ['name' => 'Физика и астрономия', 'qualification_id' => 29],
            ['name' => 'Химическая криминалистическая экспертиза', 'qualification_id' => 29],
            ['name' => 'Химическая технология органических веществ', 'qualification_id' => 29],
            ['name' => 'Химическая экспертиза и аналитический контроль производства', 'qualification_id' => 29],
            ['name' => 'Химическая, криминалистическая и экологическая экспертиза', 'qualification_id' => 29],
            ['name' => 'Химия', 'qualification_id' => 29],
            ['name' => 'Химия и наноматериалы', 'qualification_id' => 29],
            ['name' => 'Экспертиза веществ и материалов в химической инженерии', 'qualification_id' => 29],
            ['name' => 'Ядерная физика и атомная энергетика', 'qualification_id' => 29],






            // 6B06 Информационно-коммуникационные технологии
            ['name' => 'Cybersecurity (Кибербезопасность)', 'qualification_id' => 30],
            ['name' => 'Аппаратные средства защиты информации', 'qualification_id' => 30],
            ['name' => 'Информационная безопасность финансовых структур', 'qualification_id' => 30],
            ['name' => 'Информационные технологии и защита данных', 'qualification_id' => 30],
            ['name' => 'Компьютерная безопасность', 'qualification_id' => 30],
            ['name' => 'Криптографическая защита информации', 'qualification_id' => 30],
            ['name' => 'Сетевая безопасность', 'qualification_id' => 30],
            ['name' => 'Системы информационной безопасности', 'qualification_id' => 30],
            ['name' => 'Техническая защита информации', 'qualification_id' => 30],

            ['name' => 'BBA in IT in Business', 'qualification_id' => 31],
            ['name' => 'Big Data Analysis (Анализ больших данных)', 'qualification_id' => 31],
            ['name' => 'Business analytics and Big Data', 'qualification_id' => 31],
            ['name' => 'Data Science', 'qualification_id' => 31],
            ['name' => 'Digital Engineering', 'qualification_id' => 31],
            ['name' => 'Digital Engineering (3 года)', 'qualification_id' => 31],
            ['name' => 'Digital management and design', 'qualification_id' => 31],
            ['name' => 'Industrial Automation (Индустриальная автоматизация)', 'qualification_id' => 31],
            ['name' => 'IT в здравоохранении', 'qualification_id' => 31],
            ['name' => 'IT-аналитика', 'qualification_id' => 31],
            ['name' => 'IT-медицина', 'qualification_id' => 31],
            ['name' => 'IT-менеджмент', 'qualification_id' => 31],
            ['name' => 'Media Technologies (Медиа технологии)', 'qualification_id' => 31],
            ['name' => 'Mobile computing', 'qualification_id' => 31],
            ['name' => 'SMART технологии', 'qualification_id' => 31],
            ['name' => 'Software Engineering', 'qualification_id' => 31],
            ['name' => 'Автоматизация и робототехника', 'qualification_id' => 31],
            ['name' => 'Аналитика Big Data', 'qualification_id' => 31],
            ['name' => 'Архитектор программного обеспечения', 'qualification_id' => 31],
            ['name' => 'Биокомпьютинг', 'qualification_id' => 31],
            ['name' => 'Вычислительная техника и программное обеспечение', 'qualification_id' => 31],
            ['name' => 'Вычислительная техника и программное обеспечение /Smart computing', 'qualification_id' => 31],
            ['name' => 'Иммерсивные технологии', 'qualification_id' => 31],
            ['name' => 'Инженерная математика', 'qualification_id' => 31],
            ['name' => 'Интеллектуальная робототехника', 'qualification_id' => 31],
            ['name' => 'Информатика', 'qualification_id' => 31],
            ['name' => 'Информационно-программные системы', 'qualification_id' => 31],
            ['name' => 'Информационные системы', 'qualification_id' => 31],
            ['name' => 'Информационные системы и технологии', 'qualification_id' => 31],
            ['name' => 'Информационные технологии', 'qualification_id' => 31],
            ['name' => 'Информационные технологии в бизнесе', 'qualification_id' => 31],
            ['name' => 'Информационный инжиниринг в экономике', 'qualification_id' => 31],
            ['name' => 'Искусственный интеллект', 'qualification_id' => 31],
            ['name' => 'Искусственный интеллект и анализ данных', 'qualification_id' => 31],
            ['name' => 'ІТ и программирование', 'qualification_id' => 31],
            ['name' => 'Киберфизические системы', 'qualification_id' => 31],
            ['name' => 'Компьютерная инженерия', 'qualification_id' => 31],
            ['name' => 'Компьютерная инженерия (KZ + UK)', 'qualification_id' => 31],
            ['name' => 'Компьютерная мехатроника', 'qualification_id' => 31],
            ['name' => 'Компьютерные науки (Computer Science)', 'qualification_id' => 31],
            ['name' => 'Компьютерные науки и программная инженерия', 'qualification_id' => 31],
            ['name' => 'Корпоративные информационные системы', 'qualification_id' => 31],
            ['name' => 'Математическое и компьютерное моделирование', 'qualification_id' => 31],
            ['name' => 'Моделирование и конструирование виртуальной реальности', 'qualification_id' => 31],
            ['name' => 'Программная инженерия', 'qualification_id' => 31],
            ['name' => 'Телематика', 'qualification_id' => 31],
            ['name' => 'Технологии искусственного интеллекта', 'qualification_id' => 31],
            ['name' => 'Финансовая математика', 'qualification_id' => 31],
            ['name' => 'Цифровые агросистемы и комплексы', 'qualification_id' => 31],

            ['name' => 'Telecommunication systems (Телекоммуникационные системы)', 'qualification_id' => 32],
            ['name' => 'Инфокоммуникационные технологии и системы связи', 'qualification_id' => 32],
            ['name' => 'Мобильные технологии телекоммуникации', 'qualification_id' => 32],
            ['name' => 'Радиотехника, электроника и телекоммуникации', 'qualification_id' => 32],
            ['name' => 'Системы радиовещания и телевидения', 'qualification_id' => 32],
            ['name' => 'Телекоммуникационная инженерия', 'qualification_id' => 32],
            ['name' => 'Телекоммуникационные системы и сети ж.д. связи', 'qualification_id' => 32],
            ['name' => 'Электронная инженерия', 'qualification_id' => 32],




            // 6B07 Инженерные, обрабатывающие и строительные отрасли
            ['name' => 'BIM проектирование зданий и сооружений', 'qualification_id' => 33],
            ['name' => 'Архитектура', 'qualification_id' => 33],
            ['name' => 'Архитектура жилых и общественных зданий', 'qualification_id' => 33],
            ['name' => 'Водоснабжение и канализация', 'qualification_id' => 33],
            ['name' => 'Геодезия и картография', 'qualification_id' => 33],
            ['name' => 'Геоинформатика', 'qualification_id' => 33],
            ['name' => 'Геопространственная цифровая инженерия', 'qualification_id' => 33],
            ['name' => 'Дизайн архитектурной среды', 'qualification_id' => 33],
            ['name' => 'Земельный кадастр и землеустройство', 'qualification_id' => 33],
            ['name' => 'Землеустройство', 'qualification_id' => 33],
            ['name' => 'Инженерные системы зданий и сооружений', 'qualification_id' => 33],
            ['name' => 'Инженерные системы и сети', 'qualification_id' => 33],
            ['name' => 'Кадастр', 'qualification_id' => 33],
            ['name' => 'Проектирование и информационное моделирование строительных объектов', 'qualification_id' => 33],
            ['name' => 'Проектирование и строительство автомобильных дорог', 'qualification_id' => 33],
            ['name' => 'Производство строительных материалов, изделий и конструкций', 'qualification_id' => 33],
            ['name' => 'Сельское строительство', 'qualification_id' => 33],
            ['name' => 'Строительная инженерия', 'qualification_id' => 33],
            ['name' => 'Строительство', 'qualification_id' => 33],
            ['name' => 'Строительство автомобильных дорог и аэродромов', 'qualification_id' => 33],
            ['name' => 'Транспортное строительство', 'qualification_id' => 33],
            ['name' => 'Цифровая аэрофотосъемка', 'qualification_id' => 33],

            ['name' => 'Processing of mineral and technologenic raw materials', 'qualification_id' => 34],
            ['name' => 'Автоматизация и управление', 'qualification_id' => 34],
            ['name' => 'Автоматизация и управление бизнес-процессами', 'qualification_id' => 34],
            ['name' => 'Автоматизированные электромеханические системы', 'qualification_id' => 34],
            ['name' => 'Автомобили и автомобильное хозяйство', 'qualification_id' => 34],
            ['name' => 'Автомобильные дороги и аэродромы', 'qualification_id' => 34],
            ['name' => 'Автономные энергетические системы', 'qualification_id' => 34],
            ['name' => 'Атомные электрические станции и установки', 'qualification_id' => 34],
            ['name' => 'Аэрокосмическая инженерия', 'qualification_id' => 34],
            ['name' => 'Биотехнические и медицинские системы и аппараты', 'qualification_id' => 34],
            ['name' => 'Вагоны', 'qualification_id' => 34],
            ['name' => 'Возобновляемые источники энергии', 'qualification_id' => 34],
            ['name' => 'Встроенные цифровые системы управления', 'qualification_id' => 34],
            ['name' => 'Гидроэнергетика', 'qualification_id' => 34],
            ['name' => 'Железнодорожный путь и путевое хозяйство', 'qualification_id' => 34],
            ['name' => 'Индустриальная инженерия', 'qualification_id' => 34],
            ['name' => 'Инженерная механика', 'qualification_id' => 34],
            ['name' => 'Инжиниринг энергетических систем', 'qualification_id' => 34],
            ['name' => 'Интеграция и управление Smart технологиями энергосбережения и энергоэффективности в электроэнергетике', 'qualification_id' => 34],
            ['name' => 'Интернет вещей и Big Data', 'qualification_id' => 34],
            ['name' => 'Информационные технологии в электроэнергетике', 'qualification_id' => 34],
            ['name' => 'Контрольно-измерительные приборы и системы в робототехнике', 'qualification_id' => 34],
            ['name' => 'Космическая техника и технологии', 'qualification_id' => 34],
            ['name' => 'Летная эксплуатация гражданских вертолётов (пилот)', 'qualification_id' => 34],
            ['name' => 'Летная эксплуатация гражданских самолётов (пилот)', 'qualification_id' => 34],
            ['name' => 'Линейные трубопроводы', 'qualification_id' => 34],
            ['name' => 'Локомотивы', 'qualification_id' => 34],
            ['name' => 'Материаловедение и технология новых материалов', 'qualification_id' => 34],
            ['name' => 'Машиностроение', 'qualification_id' => 34],
            ['name' => 'Машины и аппараты легкой промышленности', 'qualification_id' => 34],
            ['name' => 'Медицинский инжиниринг (Медицинская техника)', 'qualification_id' => 34],
            ['name' => 'Механика и металлообработка', 'qualification_id' => 34],
            ['name' => 'Мехатроника', 'qualification_id' => 34],
            ['name' => 'Мехатроника в автомобилестроении', 'qualification_id' => 34],
            ['name' => 'Морская техника и технологии', 'qualification_id' => 34],
            ['name' => 'Мосты, тоннели и метрополитены', 'qualification_id' => 34],
            ['name' => 'Наноматериалы и нанотехнологии в химии', 'qualification_id' => 34],
            ['name' => 'Обеспечение авиационной безопасности', 'qualification_id' => 34],
            ['name' => 'Обслуживание наземного радиоэлектронного оборудования аэропортов', 'qualification_id' => 34],
            ['name' => 'Обслуживание воздушного движения и аэронавигационное обеспечение полетов', 'qualification_id' => 34],
            ['name' => 'Предпринимательство в инженерии', 'qualification_id' => 34],
            ['name' => 'Приборостроение', 'qualification_id' => 34],
            ['name' => 'Программирование и аппараты в обработке материалов и машиностроении', 'qualification_id' => 34],
            ['name' => 'Промышленная электроника и системы управления', 'qualification_id' => 34],
            ['name' => 'Промышленные системы водоподготовки', 'qualification_id' => 34],
            ['name' => 'Путевые и дорожные машины', 'qualification_id' => 34],
            ['name' => 'Робототехника и инновационные технологии в машиностроении', 'qualification_id' => 34],
            ['name' => 'Робототехника и мехатроника', 'qualification_id' => 34],
            ['name' => 'Робототехнические и интеллектуальные системы', 'qualification_id' => 34],
            ['name' => 'Робототехнические, интеллектуальные системы и приборостроение', 'qualification_id' => 34],
            ['name' => 'Роботы и робототехнические системы', 'qualification_id' => 34],
            ['name' => 'Системная инженерия', 'qualification_id' => 34],
            ['name' => 'Современные и инновационные технологии возобновляемой энергетики', 'qualification_id' => 34],
            ['name' => 'Тепловые электрические станции', 'qualification_id' => 34],
            ['name' => 'Теплоэнергетика', 'qualification_id' => 34],
            ['name' => 'Техническая эксплуатация летательных аппаратов и двигателей', 'qualification_id' => 34],
            ['name' => 'Техническая эксплуатация систем авионики летательных аппаратов', 'qualification_id' => 34],
            ['name' => 'Техническая эксплуатация, обслуживание и ремонт вагонов', 'qualification_id' => 34],
            ['name' => 'Технологии возобновляемой энергетики', 'qualification_id' => 34],
            ['name' => 'Технологические машины и оборудование (по отраслям)', 'qualification_id' => 34],
            ['name' => 'Технологическое оборудование производственных процессов', 'qualification_id' => 34],
            ['name' => 'Технология машиностроения', 'qualification_id' => 34],
            ['name' => 'Технология транспортных процессов в авиации', 'qualification_id' => 34],
            ['name' => 'Транспорт, транспортная техника и технологии', 'qualification_id' => 34],
            ['name' => 'Транспортная инженерия', 'qualification_id' => 34],
            ['name' => 'Химическая и биохимическая инженерия', 'qualification_id' => 34],
            ['name' => 'Химическая технология', 'qualification_id' => 34],
            ['name' => 'Химическая технология неорганических веществ', 'qualification_id' => 34],
            ['name' => 'Химическая технология органических веществ', 'qualification_id' => 34],
            ['name' => 'Химический инжиниринг', 'qualification_id' => 34],
            ['name' => 'Холодильные машины и системы кондиционирования', 'qualification_id' => 34],
            ['name' => 'Цифровые технологии в машиностроении', 'qualification_id' => 34],
            ['name' => 'Экоэнергетика', 'qualification_id' => 34],
            ['name' => 'Эксплуатационно-сервисная инженерия', 'qualification_id' => 34],
            ['name' => 'Эксплуатация и ремонт автомобильного транспорта', 'qualification_id' => 34],
            ['name' => 'Электроника и электротехника', 'qualification_id' => 34],
            ['name' => 'Электронные инженерные технологии', 'qualification_id' => 34],
            ['name' => 'Электрообеспечение промышленных объектов', 'qualification_id' => 34],
            ['name' => 'Электрооборудование и электрохозяйство предприятий, организаций и учреждений', 'qualification_id' => 34],
            ['name' => 'Электротехнический инжиниринг', 'qualification_id' => 34],
            ['name' => 'Электротранспортная инженерия', 'qualification_id' => 34],
            ['name' => 'Электроэнергетика', 'qualification_id' => 34],
            ['name' => 'Электроэнергетика (KZ + UK)', 'qualification_id' => 34],
            ['name' => 'Электроэнергетические системы', 'qualification_id' => 34],
            ['name' => 'Энергетика', 'qualification_id' => 34],
            ['name' => 'Энергетическая и экологическая инженерия', 'qualification_id' => 34],
            ['name' => 'Энергетическая и экологическая техника', 'qualification_id' => 34],
            ['name' => 'Энергетический инжиниринг и менеджмент', 'qualification_id' => 34],
            ['name' => 'Энергоаудит и энергоменеджмент', 'qualification_id' => 34],
            ['name' => 'Энергоснабжение нефтегазоперекачивающих комплексов', 'qualification_id' => 34],

            ['name' => 'Petroleum engineering', 'qualification_id' => 35],
            ['name' => 'Геология и разведка месторождений полезных ископаемых', 'qualification_id' => 35],
            ['name' => 'Геология и разведка природных ресурсов', 'qualification_id' => 35],
            ['name' => 'Геология нефти и газа', 'qualification_id' => 35],
            ['name' => 'Геофизические технологии и инжиниринг', 'qualification_id' => 35],
            ['name' => 'Горная инженерия', 'qualification_id' => 35],
            ['name' => 'Горное дело', 'qualification_id' => 35],
            ['name' => 'Горное и нефтегазовое дело', 'qualification_id' => 35],
            ['name' => 'Инженер 3D моделирования в горном деле', 'qualification_id' => 35],
            ['name' => 'Маркшейдерское дело', 'qualification_id' => 35],
            ['name' => 'Металлургия', 'qualification_id' => 35],
            ['name' => 'Металлургия и обогащение полезных ископаемых', 'qualification_id' => 35],
            ['name' => 'Нефтегазовая и рудная геофизика', 'qualification_id' => 35],
            ['name' => 'Нефтегазовое дело', 'qualification_id' => 35],
            ['name' => 'Нефтяная инженерия', 'qualification_id' => 35],
            ['name' => 'Нефтяная инженерия и энергоменеджмент (KZ + UK)', 'qualification_id' => 35],
            ['name' => 'Обогащение полезных ископаемых', 'qualification_id' => 35],
            ['name' => 'Строительство горных предприятий и подземных сооружений', 'qualification_id' => 35],
            ['name' => 'Технологии и инжиниринг пищевых производств', 'qualification_id' => 35],
            ['name' => 'Технология деревообработки и изделий из дерева (по областям применения)', 'qualification_id' => 35],
            ['name' => 'Технология и конструирование изделий легкой промышленности', 'qualification_id' => 35],
            ['name' => 'Технология и проектирование текстильных материалов', 'qualification_id' => 35],
            ['name' => 'Технология мукомольно-крупяных продуктов', 'qualification_id' => 35],
            ['name' => 'Технология нефтехимического производства', 'qualification_id' => 35],
            ['name' => 'Технология перерабатывающих производств', 'qualification_id' => 35],
            ['name' => 'Технология пищевых продуктов', 'qualification_id' => 35],
            ['name' => 'Технология продовольственных продуктов', 'qualification_id' => 35],
            ['name' => 'Технология фармацевтического производства', 'qualification_id' => 35],
            ['name' => 'Технология хранения и переработки зерна', 'qualification_id' => 35],

            ['name' => 'Стандартизация и сертификация (по отраслям)', 'qualification_id' => 36],
            ['name' => 'Стандартизация, сертификация и метрология (по отраслям)', 'qualification_id' => 36],





            // 6B08 Сельское хозяйство и биоресурсы
            ['name' => 'Аграрная техника и технология', 'qualification_id' => 37],
            ['name' => 'Гибридные системы электроснабжения агропромышленных объектов', 'qualification_id' => 37],
            ['name' => 'Цифровые технологии в агропромышленном комплексе', 'qualification_id' => 37],
            ['name' => 'Энергообеспечение сельского хозяйства', 'qualification_id' => 37],

            ['name' => 'Водные ресурсы и водопользование', 'qualification_id' => 38],
            ['name' => 'Мелиорация, рекультивация и охрана земель', 'qualification_id' => 38],

            ['name' => 'Менеджер животноводства', 'qualification_id' => 39],
            ['name' => 'Технология производства продуктов животноводства', 'qualification_id' => 39],

            ['name' => 'Механизация производства и переработки продукции сельского хозяйства', 'qualification_id' => 40],

            ['name' => 'Лесное дело с основами деревообработки', 'qualification_id' => 41],
            ['name' => 'Лесные ресурсы и лесоводство', 'qualification_id' => 41],
            ['name' => 'Лесные ресурсы, охотоведение и пчеловодство', 'qualification_id' => 41],
            ['name' => 'Охотоведение и звероводство', 'qualification_id' => 41],

            ['name' => 'Агрономия', 'qualification_id' => 42],
            ['name' => 'Биоинформатика', 'qualification_id' => 42],
            ['name' => 'Защита и карантин растений', 'qualification_id' => 42],
            ['name' => 'Наука о растениях и технологии', 'qualification_id' => 42],
            ['name' => 'Охрана и диагностика растений в агропромышленном комплексе', 'qualification_id' => 42],
            ['name' => 'Плодоовощеводство', 'qualification_id' => 42],
            ['name' => 'Плодоовощеводство и агропочвоведение', 'qualification_id' => 42],
            ['name' => 'Почвоведение и агрохимия', 'qualification_id' => 42],
            ['name' => 'Технология производства продукции растениеводства', 'qualification_id' => 42],

            ['name' => 'Аквакультура и водные биоресурсы', 'qualification_id' => 43],
            ['name' => 'Рыбное хозяйство и промышленное рыболовство', 'qualification_id' => 43],





            // 6В09 Ветеринария
            ['name' => 'Ветеринария', 'qualification_id' => 42],
            ['name' => 'Ветеринарная медицина', 'qualification_id' => 42],
            ['name' => 'Ветеринарная санитария', 'qualification_id' => 42],
            ['name' => 'Ветеринарно-пищевая безопасность и технологии', 'qualification_id' => 42],




            // 6B10 Здравоохранение и социальное обеспечение (медицина)
            ['name' => 'Кинезитерапия', 'qualification_id' => 43],
            ['name' => 'Лабораторная медицина', 'qualification_id' => 43],
            ['name' => 'Медико-профилактическое дело', 'qualification_id' => 43],
            ['name' => 'Медицина', 'qualification_id' => 43],
            ['name' => 'Общая медицина', 'qualification_id' => 43],
            ['name' => 'Общественное здоровье', 'qualification_id' => 43],
            ['name' => 'Общественное здравоохранение', 'qualification_id' => 43],
            ['name' => 'Педиатрия', 'qualification_id' => 43],
            ['name' => 'Сестринское дело', 'qualification_id' => 43],
            ['name' => 'Сестринское дело в реабилитологии', 'qualification_id' => 43],
            ['name' => 'Стоматология', 'qualification_id' => 43],
            ['name' => 'Фармация', 'qualification_id' => 43],
            ['name' => 'Эрготерапия', 'qualification_id' => 43],

            ['name' => 'Социальная политика и предпринимательство', 'qualification_id' => 43],
            ['name' => 'Социальная работа', 'qualification_id' => 43],





            // 6B12 Национальная безопасность и военное дело
            ['name' => 'Командная тактическая сил гражданской обороны', 'qualification_id' => 44],

            ['name' => 'Защита в чрезвычайных ситуациях', 'qualification_id' => 44],
            ['name' => 'Пожарная безопасность', 'qualification_id' => 44],
            ['name' => 'Правоохранительная деятельность', 'qualification_id' => 44],
            ['name' => 'Следственно-криминалистическая деятельность', 'qualification_id' => 44],




            // Зарубежные программы
            ['name' => 'Прикладная информатика', 'qualification_id' => 43],

            ['name' => 'Защищенные высокопроизводительные вычислительные системы', 'qualification_id' => 43],

            ['name' => 'Лечебное дело', 'qualification_id' => 43],
            ['name' => 'Педиатрия', 'qualification_id' => 43],
            ['name' => 'Стоматология', 'qualification_id' => 43],

            ['name' => 'Социально-культурная деятельность', 'qualification_id' => 43],

            ['name' => 'Математика, алгоритмы и анализ данных', 'qualification_id' => 43],

            ['name' => 'Медико-профилактическое дело', 'qualification_id' => 43],

            ['name' => 'Антропология', 'qualification_id' => 43],
            ['name' => 'Биологические науки', 'qualification_id' => 43],
            ['name' => 'История', 'qualification_id' => 43],
            ['name' => 'Математика', 'qualification_id' => 43],
            ['name' => 'Мировые языки, литература и культура', 'qualification_id' => 43],
            ['name' => 'Политология и международные отношения', 'qualification_id' => 43],
            ['name' => 'Социология', 'qualification_id' => 43],
            ['name' => 'Физика', 'qualification_id' => 43],
            ['name' => 'Химия', 'qualification_id' => 43],
            ['name' => 'Экономика', 'qualification_id' => 43],

            ['name' => 'Математические методы обработки информации и принятия решений', 'qualification_id' => 43],

            ['name' => 'Психология', 'qualification_id' => 43],

            ['name' => 'Фармация', 'qualification_id' => 43],

            ['name' => 'Русский язык и литература', 'qualification_id' => 43],

            ['name' => 'Управление природопользованием и качеством окружающей среды', 'qualification_id' => 43],
            ['name' => 'Экологические риски и природные опасности в регионах Казахстана', 'qualification_id' => 43],

            ['name' => 'Национальная экономика', 'qualification_id' => 43],

            ['name' => 'Экономика', 'qualification_id' => 43],

            ['name' => 'Юриспруденция', 'qualification_id' => 43],

            ['name' => 'Физика элементарных частиц и космология', 'qualification_id' => 43],




            // 6B11 Услуги
            ['name' => 'Безопасность жизнедеятельности и защита окружающей среды','qualification_id' => 56],
            ['name' => 'Инженерная экология и безопасность в энергетике', 'qualification_id' => 56],
            ['name' => 'Инновационное управление безопасностью ЧС природного и техногенного характера', 'qualification_id' => 56],
            ['name' => 'Промышленная безопасность', 'qualification_id' => 56],
            ['name' => 'Промышленная, экологическая и пожарная безопасность', 'qualification_id' => 56],
            ['name' => 'Экоаналитика в отраслях', 'qualification_id' => 56],


            ['name' => 'IT–технологии в сфере сервиса', 'qualification_id' => 58],
            ['name' => 'Tourism Guide Service', 'qualification_id' => 58],
            ['name' => 'Гостиничный и ресторанный бизнес', 'qualification_id' => 58],
            ['name' => 'Ивент-менеджмент', 'qualification_id' => 58],
            ['name' => 'Культурно-досуговая работа', 'qualification_id' => 58],
            ['name' => 'Международный и внутренний туризм', 'qualification_id' => 58],
            ['name' => 'Международный туризм', 'qualification_id' => 58],
            ['name' => 'Менеджмент инноваций туризма и гостеприимства', 'qualification_id' => 58],
            ['name' => 'Менеджмент туристских дестинаций', 'qualification_id' => 58],
            ['name' => 'Организация индустрии туризма и гостеприимства', 'qualification_id' => 58],
            ['name' => 'Организация экскурсионных услуг и индивидуальных туров', 'qualification_id' => 58],
            ['name' => 'Ресторанно-отельный бизнес', 'qualification_id' => 58],
            ['name' => 'Ресторанное дело и гостиничный бизнес', 'qualification_id' => 58],
            ['name' => 'Спортивно-оздоровительный фитнес', 'qualification_id' => 58],
            ['name' => 'Спортивный и оздоровительный фитнес', 'qualification_id' => 58],
            ['name' => 'Спортивный туризм', 'qualification_id' => 58],
            ['name' => 'Туризм', 'qualification_id' => 58],
            ['name' => 'Туризм и Events Management', 'qualification_id' => 58],
            ['name' => 'Туризм и гостеприимство', 'qualification_id' => 58],
            ['name' => 'Управление и организация мероприятий', 'qualification_id' => 58],
            ['name' => 'Устойчивый туризм', 'qualification_id' => 58],


            ['name' => 'Бизнес-логистика', 'qualification_id' => 59],
            ['name' => 'Логистика', 'qualification_id' => 59],
            ['name' => 'Логистика (по отраслям)', 'qualification_id' => 59],
            ['name' => 'Логистика на транспорте', 'qualification_id' => 59],
            ['name' => 'Организация авиационных перевозок', 'qualification_id' => 59],
            ['name' => 'Организация аэропортовой деятельности', 'qualification_id' => 59],
            ['name' => 'Организация дорожного движения', 'qualification_id' => 59],
            ['name' => 'Организация и управление логистикой', 'qualification_id' => 59],
            ['name' => 'Организация перевозок, движения и эксплуатация транспорта', 'qualification_id' => 59],
            ['name' => 'Транспортная логистика', 'qualification_id' => 59],
            ['name' => 'Управление услугами в отрасли', 'qualification_id' => 59],
        ];

        DB::table('specializations')->insert($specialties);
    }
}
