<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class UsersTableSeeder extends Seeder
{
    public function run()
    {
        $users = [
            ['username' => 'Rauan Akhmetov', 'email' => 'rauan.akhmetov@example.com'],
            ['username' => 'Alisher Eschanov', 'email' => 'alisher.eschanov@example.com'],
            ['username' => 'Dimash Kudaibergen', 'email' => 'dimash.kudaibergen@example.com'],
            ['username' => 'Gennady Golovkin', 'email' => 'gennady.golovkin@example.com'],
            ['username' => 'Ilya Ilyin', 'email' => 'ilya.ilyin@example.com'],
            ['username' => 'Serik Sapiyev', 'email' => 'serik.sapiyev@example.com'],
            ['username' => 'Olga Rypakova', 'email' => 'olga.rypakova@example.com'],
            ['username' => 'Bibigul Tulegenova', 'email' => 'bibigul.tulegenova@example.com'],
            ['username' => 'Daneliya Tuleshova', 'email' => 'daneliya.tuleshova@example.com'],
            ['username' => 'Yerlan Sagymbayev', 'email' => 'yerlan.sagymbayev@example.com'],
            ['username' => 'Sergey Kazanov', 'email' => 'sergey.kazanov@example.com'],
            ['username' => 'Kanat Islam', 'email' => 'kanat.islam@example.com'],
            ['username' => 'Zhansaya Abdumalik', 'email' => 'zhansaya.abdumalik@example.com'],
            ['username' => 'Rakhimzhan Koshkarbaev', 'email' => 'rakhimzhan.koshkarbaev@example.com'],
            ['username' => 'Bauyrzhan Momyshuly', 'email' => 'bauyrzhan.momyshuly@example.com'],
            ['username' => 'Abay Kunanbayev', 'email' => 'abay.kunanbayev@example.com'],
            ['username' => 'Mukhtar Auezov', 'email' => 'mukhtar.auezov@example.com'],
            ['username' => 'Shokan Ualikhanov', 'email' => 'shokan.ualikhanov@example.com'],
            ['username' => 'Aisuluu Tynybekova', 'email' => 'aisuluu.tynybekova@example.com'],
            ['username' => 'Alexey Poltoranin', 'email' => 'alexey.poltoranin@example.com'],
            ['username' => 'Askar Zhumagaliyev', 'email' => 'askar.zhumagaliyev@example.com'],
            ['username' => 'Yerlan Nigmatulin', 'email' => 'yerlan.nigmatulin@example.com'],
            ['username' => 'Madina Sultanova', 'email' => 'madina.sultanova@example.com'],
            ['username' => 'Yerlan Mukashev', 'email' => 'yerlan.mukashev@example.com'],
            ['username' => 'Aigul Bekmukhanova', 'email' => 'aigul.bekmukhanova@example.com'],
            ['username' => 'Bolat Zhakupov', 'email' => 'bolat.zhakupov@example.com'],
            ['username' => 'Saule Abisheva', 'email' => 'saule.abisheva@example.com'],
            ['username' => 'Kanat Dosmukhamedov', 'email' => 'kanat.dosmukhamedov@example.com'],
            ['username' => 'Diana Karimova', 'email' => 'diana.karimova@example.com'],
            ['username' => 'Nurzhan Kairatov', 'email' => 'nurzhan.kairatov@example.com'],
            ['username' => 'Gaukhar Serikbayeva', 'email' => 'gaukhar.serikbayeva@example.com'],
            ['username' => 'Ruslan Saparov', 'email' => 'ruslan.saparov@example.com'],
            ['username' => 'Askhat Tuleuov', 'email' => 'askhat.tuleuov@example.com'],
            ['username' => 'Aruzhan Nurtayeva', 'email' => 'aruzhan.nurtayeva@example.com'],
            ['username' => 'Zhanar Kassenova', 'email' => 'zhanar.kassenova@example.com'],
            ['username' => 'Daulet Amankulov', 'email' => 'daulet.amankulov@example.com'],
            ['username' => 'Karim Alzhanov', 'email' => 'karim.alzhanov@example.com'],
            ['username' => 'Serik Zhumabekov', 'email' => 'serik.zhumabekov@example.com'],
            ['username' => 'Marat Abilov', 'email' => 'marat.abilov@example.com'],
            ['username' => 'Aliya Zhanibekova', 'email' => 'aliya.zhanibekova@example.com'],
            ['username' => 'Vladimir Petrov', 'email' => 'vladimir.petrov@example.com'],
            ['username' => 'Olga Smirnova', 'email' => 'olga.smirnova@example.com'],
            ['username' => 'Dmitry Ivanov', 'email' => 'dmitry.ivanov@example.com'],
            ['username' => 'Natalia Sokolova', 'email' => 'natalia.sokolova@example.com'],
            ['username' => 'Alexey Kuznetsov', 'email' => 'alexey.kuznetsov@example.com'],
            ['username' => 'Tatiana Morozova', 'email' => 'tatiana.morozova@example.com'],
            ['username' => 'Sergey Volkov', 'email' => 'sergey.volkov@example.com'],
            ['username' => 'Elena Polyakova', 'email' => 'elena.polyakova@example.com'],
            ['username' => 'Roman Kovalev', 'email' => 'roman.kovalev@example.com'],
            ['username' => 'Evgenia Fedorova', 'email' => 'evgenia.fedorova@example.com'],
            ['username' => 'Maxim Nikitin', 'email' => 'maxim.nikitin@example.com'],
            ['username' => 'Ekaterina Egorova', 'email' => 'ekaterina.egorova@example.com'],
            ['username' => 'Arman Sarsembayev', 'email' => 'arman.sarsembayev@example.com'],
            ['username' => 'Aidos Yernazarov', 'email' => 'aidos.yernazarov@example.com'],
            ['username' => 'Daniyar Tulepov', 'email' => 'daniyar.tulepov@example.com'],
            ['username' => 'Zarina Mussayeva', 'email' => 'zarina.mussayeva@example.com'],
            ['username' => 'Bibigul Ospanova', 'email' => 'bibigul.ospanova@example.com'],
            ['username' => 'Yerbolat Asanov', 'email' => 'yerbolat.asanov@example.com'],
            ['username' => 'Nurzhan Esenov', 'email' => 'nurzhan.esenov@example.com'],
            ['username' => 'Altynay Sadykova', 'email' => 'altynay.sadykova@example.com'],
            ['username' => 'Zhanibek Kazybayev', 'email' => 'zhanibek.kazybayev@example.com'],
            ['username' => 'Moldir Kenzhebekova', 'email' => 'moldir.kenzhebekova@example.com'],
            ['username' => 'Kamila Tulegenova', 'email' => 'kamila.tulegenova@example.com'],
            ['username' => 'Aizhan Yeszhanova', 'email' => 'aizhan.yeszhanova@example.com'],
            ['username' => 'Bakytzhan Mukhtarov', 'email' => 'bakytzhan.mukhtarov@example.com'],
            ['username' => 'Dauletzhan Zhumatayev', 'email' => 'dauletzhan.zhumatayev@example.com'],
            ['username' => 'Batyrbek Alimzhanov', 'email' => 'batyrbek.alimzhanov@example.com'],
            ['username' => 'Zhansaya Sarsenova', 'email' => 'zhansaya.sarsenova@example.com'],
            ['username' => 'Nurzhan Tulegenov', 'email' => 'nurzhan.tulegenov@example.com'],
            ['username' => 'Saule Abdigalieva', 'email' => 'saule.abdigalieva@example.com'],
            ['username' => 'Talgat Mukhamedzhanov', 'email' => 'talgat.mukhamedzhanov@example.com'],
            ['username' => 'Gulzhan Abisheva', 'email' => 'gulzhan.abisheva@example.com'],
            ['username' => 'Yerzhan Karabayev', 'email' => 'yerzhan.karabayev@example.com'],
            ['username' => 'Aruzhan Bekzatova', 'email' => 'aruzhan.bekzatova@example.com'],
            ['username' => 'Bolat Serikov', 'email' => 'bolat.serikov@example.com'],
            ['username' => 'Madina Ospanova', 'email' => 'madina.ospanova@example.com'],
            ['username' => 'Zhanibek Kassenov', 'email' => 'zhanibek.kassenov@example.com'],
            ['username' => 'Aida Zhakupova', 'email' => 'aida.zhakupova@example.com'],
            ['username' => 'Miras Amankulov', 'email' => 'miras.amankulov@example.com'],
            ['username' => 'Zhanel Mukasheva', 'email' => 'zhanel.mukasheva@example.com'],
            ['username' => 'Yerassyl Zhumabayev', 'email' => 'yerassyl.zhumabayev@example.com'],
            ['username' => 'Anastasia Petrova', 'email' => 'anastasia.petrova@example.com'],
            ['username' => 'Vladimir Sokolov', 'email' => 'vladimir.sokolov@example.com'],
            ['username' => 'Elena Ivanova', 'email' => 'elena.ivanova@example.com'],
            ['username' => 'Dmitry Kuznetsov', 'email' => 'dmitry.kuznetsov@example.com'],
            ['username' => 'Tatyana Smirnova', 'email' => 'tatyana.smirnova@example.com'],
            ['username' => 'Mikhail Fedorov', 'email' => 'mikhail.fedorov@example.com'],
            ['username' => 'Olga Egorova', 'email' => 'olga.egorova@example.com'],
            ['username' => 'Sergey Antonov', 'email' => 'sergey.antonov@example.com'],
            ['username' => 'Natalya Vasilyeva', 'email' => 'natalya.vasilyeva@example.com'],
            ['username' => 'Arman Tulegenov', 'email' => 'arman.tulegenov@example.com'],
            ['username' => 'Alina Kassymova', 'email' => 'alina.kassymova@example.com'],
            ['username' => 'Dias Sadykov', 'email' => 'dias.sadykov@example.com'],
            ['username' => 'Aigerim Zhantasova', 'email' => 'aigerim.zhantasova@example.com'],
            ['username' => 'Erbolat Bektasov', 'email' => 'erbolat.bektasov@example.com'],
            ['username' => 'Gulnaz Alimzhanova', 'email' => 'gulnaz.alimzhanova@example.com'],
            ['username' => 'Alexey Morozov', 'email' => 'alexey.morozov@example.com'],
            ['username' => 'Yulia Nikolaeva', 'email' => 'yulia.nikolaeva@example.com'],
            ['username' => 'Konstantin Pavlov', 'email' => 'konstantin.pavlov@example.com'],
            ['username' => 'Irina Mikhailova', 'email' => 'irina.mikhailova@example.com'],
            ['username' => 'Baurzhan Tasmagambetov', 'email' => 'baurzhan.tasmagambetov@example.com'],
            ['username' => 'Altynai Saparova', 'email' => 'altynai.saparova@example.com'],
            ['username' => 'Bakhtiyar Amangeldin', 'email' => 'bakhtiyar.amangeldin@example.com'],
            ['username' => 'Dana Zharkynova', 'email' => 'dana.zharkynova@example.com'],
            ['username' => 'Artem Petrov', 'email' => 'artem.petrov@example.com'],
            ['username' => 'Maria Fomina', 'email' => 'maria.fomina@example.com'],
            ['username' => 'Stepan Orlov', 'email' => 'stepan.orlov@example.com'],
            ['username' => 'Nadezhda Belyaeva', 'email' => 'nadezhda.belyaeva@example.com'],
            ['username' => 'Nikolay Popov', 'email' => 'nikolay.popov@example.com'],
            ['username' => 'Svetlana Simonova', 'email' => 'svetlana.simonova@example.com'],
            ['username' => 'Maxim Ivanov', 'email' => 'maxim.ivanov@example.com'],
            ['username' => 'Ekaterina Makarova', 'email' => 'ekaterina.makarova@example.com'],
            ['username' => 'Andrey Lebedev', 'email' => 'andrey.lebedev@example.com'],
            ['username' => 'Polina Vinogradova', 'email' => 'polina.vinogradova@example.com'],
        ];

        foreach ($users as $user) {
            DB::table('users')->insert([
                'username' => $user['username'],
                'email' => $user['email'],
                'password' => Hash::make('password123'),
                'is_banned'  => rand(0, 1), 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
        }
    }
}
